config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path_names: { sign_in: 'login',
    sign_out: 'logout',
    password: 'secret',
    confirmation: 'verification',
    unlock: 'unblock',
    registration: 'register',
    sign_up: 'cmon_let_me_in' },
    controllers: {
      registrations: 'users/registrations'
    }
  resources :posts do
    member do
      put "like", to: "posts#like" 
    end
  end
  root 'posts#index'
  get 'static_pages/index'
  get 'privacy_policy', to: 'static_pages#privacy_policy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, :content, presence: true
  has_rich_text :content
  belongs_to :user
  acts_as_votable
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  skip_before_action :authenticate_user!, :only => [:index, :privacy_policy]
  before_action :set_post, only: [:show, :edit, :update, :destroy, :like]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end
  
  def like
    if current_user.voted_for? @post
      @post.unliked_by current_user
    else
      @post.liked_by current_user
    end
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
    if @post.user_id == current_user.id
    else
      redirect_to root_path, notice: 'You cannot!'
    end  
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    if @post.user_id == current_user.id
      respond_to do |format|
        if @post.update(post_params)
          format.html { redirect_to @post, notice: 'Post was successfully updated.' }
          format.json { render :show, status: :ok, location: @post }
        else
          format.html { render :edit }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to root_path, notice: 'You are not authorized!'
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    if @post.user_id == current_user.id
      @post.destroy
      respond_to do |format|
        format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      redirect_to root_path, notice: 'You are not authorized!'
    end  
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :content)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@post) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :title
    /= f.input :content
    = f.input :content, as: :rich_text_area

  .form-actions
    = f.button :submit

app/views/posts/_like_link.html.haml
- vote_text = current_user&.voted_for?(@post) ? "Unlike" : "Like"
= link_to vote_text, like_post_path(@post), method: :put, remote: :true

app/views/posts/_likes.html.haml
= pluralize(@post.get_upvotes.size, "Like")

app/views/posts/_post.html.haml
.card
  .card-header
    %i
    = post.user.nickname
    %p
    = link_to post.title, post
    /= post.title
  .card-body
    = post.content
  .card-footer
    = post.created_at
    /= link_to 'Показать', post
    /= link_to 'Редактировать', edit_post_path(post)
    - if current_user
      - if post.user == current_user  
        %p
        = link_to edit_post_path(post), class: 'btn btn-sm btn-warning' do
          .fa.fa-edit
          Редактировать
        /= link_to 'Удалить', post, method: :delete, data: { confirm: 'Вы уверены?' }
        = link_to post, method: :delete, data: { confirm: 'Вы уверены?' }, class: 'btn btn-sm btn-danger' do
          .fa.fa-trash
          Удалить
  .card-footer
    - if action_name == 'show'
    
      = content_tag "div", id: "like-count" do
        = render 'posts/likes', post: post
      = content_tag "div", id: "like-link" do
        = render 'posts/like_link', post: post
    - else
      %b
      Рейтинг:
      = post.get_upvotes.size
%p  

app/views/posts/edit.html.haml
%h1 Editing post

= render 'form'

= link_to 'Show', @post
\|
= link_to 'Back', posts_path

app/views/posts/index.html.haml
%h1 Все посты

- @posts.each do |post|
  =render 'posts/post', post: post

- if current_user
  = link_to 'New Post', new_post_path, class: 'btn btn-success'

app/views/posts/like.js.haml
$("#like-count").html("#{j render 'posts/likes', post: @post}");
$("#like-link").html("#{j render 'posts/like_link', post: @post}");

app/views/posts/new.html.haml
%h1 New post

= render 'form'

= link_to 'Back', posts_path

app/views/posts/show.html.haml
= render 'posts/post', post: @post

= link_to 'Back', posts_path

/%p#notice= notice

/%p
/  %b Title:
/  = @post.title
/%p
/  %b Content:
/  = @post.content

/= link_to 'Edit', edit_post_path(@post)
/\|
/= link_to 'Back', posts_path